export type SupportedLocale = "ru" | "en";

export const defaultLocale: SupportedLocale = "ru";
export const supportedLocales: SupportedLocale[] = ["ru", "en"];

export const themeTokens = {
  colors: {
    ink: "#17130f",
    muted: "#6d6259",
    paper: "#f7f1e8",
    surface: "#fffaf3",
    accent: "#7d2f1b"
  },
  spacing: {
    field: "12px",
    panel: "24px"
  },
  borderRadius: {
    control: "6px",
    panel: "8px"
  },
  fontFamily: {
    body: ['"Inter"', "Arial", "sans-serif"],
    display: ["Georgia", '"Times New Roman"', "serif"]
  }
} as const;

export function normalizeLocale(locale: string | undefined): SupportedLocale {
  if (locale?.toLowerCase().startsWith("en")) {
    return "en";
  }

  return defaultLocale;
}

const messages = {
  ru: {
    protectedHomeTitle: "Рабочее место стилиста",
    protectedHomeSubtitle: "Защищенный экран для Клиентов и Записей.",
    onboardingTitle: "Настройте рабочее место",
    onboardingSubtitle: "Подтвердите язык, часовой пояс и адрес салона перед началом работы.",
    settingsTitle: "Настройки стилиста",
    settingsSubtitle: "Измените язык приложения, часовой пояс и адрес салона.",
    languageLabel: "Язык приложения",
    languageRussian: "Русский",
    languageEnglish: "English",
    timezoneLabel: "Часовой пояс",
    addressLabel: "Адрес салона или бизнеса",
    optionalSetupTitle: "Можно настроить позже",
    optionalSetupBody: "Google Calendar, напоминания стилиста и меню услуг необязательны после онбординга.",
    saveOnboarding: "Сохранить и продолжить",
    saveSettings: "Сохранить настройки",
    timezoneRequired: "Подтвердите часовой пояс.",
    clientsTitle: "Клиенты",
    clientsSubtitle: "Создавайте, ищите и обновляйте Client Profiles для своего рабочего места.",
    clientSearchLabel: "Поиск по имени или телефону",
    clientSearchPlaceholder: "Анна или +1...",
    newClientTitle: "Новый Client Profile",
    editClientTitle: "Client Profile",
    clientNameLabel: "Имя Клиента",
    clientPhoneLabel: "Телефон",
    clientEmailLabel: "Email",
    clientAddressLabel: "Адрес",
    clientNoteLabel: "Client Note",
    saveClient: "Сохранить Клиента",
    createClient: "Создать Клиента",
    clearClientForm: "Очистить форму",
    deleteClient: "Удалить Клиента",
    noClientsTitle: "Пока нет Клиентов",
    noClientsBody: "Создайте первого Клиента с одним именем, затем добавьте детали позже.",
    noClientResults: "Нет Клиентов по этому поиску.",
    duplicatePhoneTitle: "Телефон уже используется",
    duplicatePhoneBody: "У другого Клиента уже есть этот телефон. Можно сохранить всё равно.",
    duplicatePhoneContinue: "Сохранить всё равно",
    cancel: "Отмена",
    clientNameRequired: "Добавьте имя Клиента.",
    clientSaved: "Client Profile сохранён.",
    clientDeleted: "Client Profile удалён.",
    homeAppointmentsTitle: "Сегодня и незавершённые",
    homeAppointmentsSubtitle: "Записи на сегодня и прошлые scheduled Записи, которым нужен итог.",
    calendarTitle: "Календарь",
    calendarSubtitle: "Просматривайте Записи по дням.",
    previousDay: "Назад",
    nextDay: "Вперёд",
    appointmentsEmptyTitle: "Нет Записей",
    appointmentsEmptyBody: "Создайте Запись, чтобы увидеть её здесь.",
    newAppointmentTitle: "Новая Запись",
    newAppointmentSubtitle: "Выберите основного Клиента, время и локацию.",
    primaryClientLabel: "Основной Клиент",
    additionalClientsLabel: "Дополнительные Клиенты",
    inlineClientLabel: "Создать минимального Клиента",
    appointmentStartLabel: "Начало",
    appointmentEndLabel: "Окончание",
    appointmentLocationLabel: "Локация",
    appointmentInSalon: "В салоне",
    appointmentAtHome: "На дому",
    appointmentAddressLabel: "Адрес Записи",
    createAppointment: "Создать Запись",
    appointmentClientRequired: "Выберите Клиента или создайте минимального Клиента.",
    appointmentStartRequired: "Добавьте время начала.",
    appointmentSaved: "Запись создана.",
    appointmentConflictWarning: "Запись создана, но есть конфликт времени.",
    appointmentMapUnavailable: "Для этой Записи нет адреса.",
    openInMaps: "Открыть в Google Maps",
    appointmentStatus_scheduled: "Scheduled",
    appointmentStatus_completed: "Completed",
    appointmentStatus_canceled: "Canceled",
    appointmentStatus_noShow: "No-show",
    appointmentNotePlaceholder: "Заметка к Записи",
    serviceMenuTitle: "Меню услуг",
    serviceMenuSubtitle: "Создавайте стандартные услуги с ценой по умолчанию.",
    serviceMenuNameLabel: "Название услуги",
    serviceMenuPriceLabel: "Цена по умолчанию",
    serviceMenuEmptyTitle: "Меню услуг пустое",
    serviceMenuEmptyBody: "Добавьте часто используемую услугу, чтобы быстрее заполнять Записи.",
    saveServiceMenuItem: "Сохранить услугу",
    createServiceMenuItem: "Создать услугу",
    clearServiceMenuForm: "Очистить услугу",
    deleteServiceMenuItem: "Удалить услугу",
    serviceMenuItemSaved: "Услуга сохранена.",
    serviceMenuItemDeleted: "Услуга удалена.",
    serviceNameRequired: "Добавьте название услуги.",
    appointmentServicesTitle: "Услуги",
    appointmentServiceClientLabel: "Клиент для услуги",
    appointmentServiceNameLabel: "Услуга",
    appointmentServicePriceLabel: "Цена",
    appointmentServiceNoteLabel: "Заметка к услуге",
    appointmentServiceSaved: "Услуга добавлена.",
    addAdHocService: "Добавить разовую услугу",
    addMenuService: "Добавить из меню",
    deleteAppointmentService: "Удалить услугу",
    colorFormulaLabel: "Формула цвета",
    colorFormulaPlacementLabel: "Зона нанесения",
    addColorFormula: "Добавить формулу",
    saveColorFormula: "Сохранить формулу",
    deleteColorFormula: "Удалить формулу",
    colorFormulaRequired: "Добавьте текст формулы.",
    copyCompletedServices: "Скопировать услуги из завершённой Записи",
    appointmentServiceTotal: "Итого услуг",
    appointmentFinalTotal: "Финальный итог",
    appointmentFinalTotalOverride: "Переопределить финальный итог",
    saveFinalTotal: "Сохранить итог",
    clearFinalTotalOverride: "Сумма услуг",
    markCompleted: "Completed",
    markCanceled: "Canceled",
    markNoShow: "No-show",
    markScheduled: "Scheduled",
    saveAppointmentNote: "Сохранить заметку",
    composeClientReminder: "SMS-напоминание",
    clientReminderMissingPhone: "У основного Клиента нет телефона для SMS.",
    deleteAppointment: "Удалить Запись",
    makePrimary: "Сделать основным",
    removeClientFromAppointment: "Убрать Клиента",
    addClientToAppointment: "Добавить Клиента",
    signInTitle: "Вход для стилиста",
    signUpTitle: "Регистрация стилиста",
    verifyEmailTitle: "Подтвердите email",
    missingEnvTitle: "Нужна настройка окружения",
    missingEnvBody: "Добавьте ключ Clerk перед запуском приложения.",
    profileShareTitle: "Профиль Клиента",
    profileSharePlaceholder: "Публичная страница Profile Share готова к подключению данных.",
    createProfileShare: "Создать Profile Share",
    openProfileShare: "Открыть Profile Share",
    revokeProfileShare: "Отозвать Profile Share",
    shareImageLanguageLabel: "Язык Share Image",
    generateShareImage: "Создать Share Image",
    profileShareNotFound: "Profile Share недоступен.",
    profileShareUpcomingTitle: "Будущие записи",
    profileShareLastCompletedTitle: "Последняя завершённая запись",
    profileShareNoUpcoming: "Будущих записей нет.",
    profileShareNoCompleted: "Завершённых записей пока нет.",
    profileShareServicesTitle: "Услуги и формулы",
    profileSharePhotosTitle: "Фото",
    profileSharePhotosEmpty: "Сохранённых фото для показа пока нет.",
    switchToRussian: "Русский",
    switchToEnglish: "English"
  },
  en: {
    protectedHomeTitle: "Stylist workspace",
    protectedHomeSubtitle: "Protected screen for Clients and Appointments.",
    onboardingTitle: "Set up your workspace",
    onboardingSubtitle: "Confirm language, timezone, and salon address before using the app.",
    settingsTitle: "Stylist settings",
    settingsSubtitle: "Edit app language, timezone, and salon address.",
    languageLabel: "App language",
    languageRussian: "Русский",
    languageEnglish: "English",
    timezoneLabel: "Timezone",
    addressLabel: "Salon or business address",
    optionalSetupTitle: "Can be set up later",
    optionalSetupBody: "Google Calendar, Stylist Reminders, and Service Menu Items stay optional after onboarding.",
    saveOnboarding: "Save and continue",
    saveSettings: "Save settings",
    timezoneRequired: "Confirm a timezone.",
    clientsTitle: "Clients",
    clientsSubtitle: "Create, search, and update Client Profiles for your workspace.",
    clientSearchLabel: "Search by name or phone",
    clientSearchPlaceholder: "Anna or +1...",
    newClientTitle: "New Client Profile",
    editClientTitle: "Client Profile",
    clientNameLabel: "Client name",
    clientPhoneLabel: "Phone",
    clientEmailLabel: "Email",
    clientAddressLabel: "Address",
    clientNoteLabel: "Client Note",
    saveClient: "Save Client",
    createClient: "Create Client",
    clearClientForm: "Clear form",
    deleteClient: "Delete Client",
    noClientsTitle: "No Clients yet",
    noClientsBody: "Create the first Client with only a name, then add details later.",
    noClientResults: "No Clients match this search.",
    duplicatePhoneTitle: "Phone already used",
    duplicatePhoneBody: "Another Client already has this phone number. You can save anyway.",
    duplicatePhoneContinue: "Save anyway",
    cancel: "Cancel",
    clientNameRequired: "Add a Client name.",
    clientSaved: "Client Profile saved.",
    clientDeleted: "Client Profile deleted.",
    homeAppointmentsTitle: "Today and unresolved",
    homeAppointmentsSubtitle: "Today's Appointments and past scheduled Appointments that still need an outcome.",
    calendarTitle: "Calendar",
    calendarSubtitle: "Browse Appointments by day.",
    previousDay: "Previous",
    nextDay: "Next",
    appointmentsEmptyTitle: "No Appointments",
    appointmentsEmptyBody: "Create an Appointment to see it here.",
    newAppointmentTitle: "New Appointment",
    newAppointmentSubtitle: "Choose the primary Client, time, and location.",
    primaryClientLabel: "Primary Client",
    additionalClientsLabel: "Additional Clients",
    inlineClientLabel: "Create minimal Client inline",
    appointmentStartLabel: "Start time",
    appointmentEndLabel: "End time",
    appointmentLocationLabel: "Location",
    appointmentInSalon: "In salon",
    appointmentAtHome: "At home",
    appointmentAddressLabel: "Appointment address",
    createAppointment: "Create Appointment",
    appointmentClientRequired: "Choose a Client or create a minimal Client.",
    appointmentStartRequired: "Add a start time.",
    appointmentSaved: "Appointment created.",
    appointmentConflictWarning: "Appointment created, but there is a time conflict.",
    appointmentMapUnavailable: "This Appointment has no address.",
    openInMaps: "Open in Google Maps",
    appointmentStatus_scheduled: "Scheduled",
    appointmentStatus_completed: "Completed",
    appointmentStatus_canceled: "Canceled",
    appointmentStatus_noShow: "No-show",
    appointmentNotePlaceholder: "Appointment note",
    serviceMenuTitle: "Service Menu",
    serviceMenuSubtitle: "Create standard services with default prices.",
    serviceMenuNameLabel: "Service name",
    serviceMenuPriceLabel: "Default price",
    serviceMenuEmptyTitle: "No Service Menu Items",
    serviceMenuEmptyBody: "Add a common service to fill Appointments faster.",
    saveServiceMenuItem: "Save Service",
    createServiceMenuItem: "Create Service",
    clearServiceMenuForm: "Clear service",
    deleteServiceMenuItem: "Delete Service",
    serviceMenuItemSaved: "Service saved.",
    serviceMenuItemDeleted: "Service deleted.",
    serviceNameRequired: "Add a service name.",
    appointmentServicesTitle: "Services",
    appointmentServiceClientLabel: "Service Client",
    appointmentServiceNameLabel: "Service",
    appointmentServicePriceLabel: "Price",
    appointmentServiceNoteLabel: "Service note",
    appointmentServiceSaved: "Service added.",
    addAdHocService: "Add ad hoc Service",
    addMenuService: "Add from menu",
    deleteAppointmentService: "Delete Service",
    colorFormulaLabel: "Color Formula",
    colorFormulaPlacementLabel: "Placement",
    addColorFormula: "Add Formula",
    saveColorFormula: "Save Formula",
    deleteColorFormula: "Delete Formula",
    colorFormulaRequired: "Add formula text.",
    copyCompletedServices: "Copy services from completed Appointment",
    appointmentServiceTotal: "Services total",
    appointmentFinalTotal: "Final total",
    appointmentFinalTotalOverride: "Override final total",
    saveFinalTotal: "Save total",
    clearFinalTotalOverride: "Use services total",
    markCompleted: "Completed",
    markCanceled: "Canceled",
    markNoShow: "No-show",
    markScheduled: "Scheduled",
    saveAppointmentNote: "Save note",
    composeClientReminder: "SMS reminder",
    clientReminderMissingPhone: "The primary Client has no phone number for SMS.",
    deleteAppointment: "Delete Appointment",
    makePrimary: "Make primary",
    removeClientFromAppointment: "Remove Client",
    addClientToAppointment: "Add Client",
    signInTitle: "Stylist sign in",
    signUpTitle: "Stylist sign up",
    verifyEmailTitle: "Verify email",
    missingEnvTitle: "Environment setup required",
    missingEnvBody: "Add the Clerk key before running the app.",
    profileShareTitle: "Client Profile",
    profileSharePlaceholder: "The public Profile Share page is ready for data wiring.",
    createProfileShare: "Create Profile Share",
    openProfileShare: "Open Profile Share",
    revokeProfileShare: "Revoke Profile Share",
    shareImageLanguageLabel: "Share Image language",
    generateShareImage: "Generate Share Image",
    profileShareNotFound: "Profile Share is unavailable.",
    profileShareUpcomingTitle: "Upcoming Appointments",
    profileShareLastCompletedTitle: "Last completed Appointment",
    profileShareNoUpcoming: "No upcoming Appointments.",
    profileShareNoCompleted: "No completed Appointments yet.",
    profileShareServicesTitle: "Services and formulas",
    profileSharePhotosTitle: "Photos",
    profileSharePhotosEmpty: "No stored photos are selected for sharing yet.",
    switchToRussian: "Русский",
    switchToEnglish: "English"
  }
} as const;

export type MessageKey = keyof (typeof messages)["ru"];

export function t(locale: SupportedLocale, key: MessageKey): string {
  return messages[locale][key];
}

export type ClientReminderMessageInput = {
  locale: SupportedLocale;
  appointmentTime: string;
  location: string;
};

export function buildClientReminderMessage(input: ClientReminderMessageInput): string {
  if (input.locale === "en") {
    return `Reminder: your appointment is scheduled for ${input.appointmentTime}. Location: ${input.location}.`;
  }

  return `Напоминание: ваша запись назначена на ${input.appointmentTime}. Адрес: ${input.location}.`;
}

export function buildSmsComposerUrl(phone: string, body: string): string {
  const recipient = phone.trim().replace(/[^\d+]/g, "");

  return `sms:${recipient}?body=${encodeURIComponent(body)}`;
}
